spring.application.name=skincare-ecommerce

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/skincare_ecommerce?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Hkz8b4YQ7Xx0q5pK/HdT6WypZ6LskpYx7mR8sXxz9v8QFUVjN8dj5HqC7dC4dHD3HTt+RkM0+VcYAz5NnXx8bg==
jwt.expiration=86400000

otp.expiration=300000
otp.max-attempts=3

#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=sd1625741@gmail.com
#spring.mail.password=tvex zkbp oiqv xtjh
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=smtp.hostinger.com
spring.mail.port=587
spring.mail.username=noreply@dermedicostore.in
spring.mail.password=Qawsedrftg@321
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.hostinger.com

razorpay.key.id=rzp_test_c62AsoWrgvuVIF
razorpay.key.secret=pEHKmgZuHdPpGOISlZOFer99

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB


file.upload-dir=uploads/
spring.web.resources.static-locations=classpath:/static/,file:uploads/

file.upload.dir=uploads/

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

